name: CD

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Get release version
      id: get-version
      uses: dawidd6/action-get-tag@v1

    - name: Install .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        # Fixed version, workaround for https://github.com/dotnet/core/issues/7176
        dotnet-version: 6.0.100

    - name: Build & publish
      run: dotnet publish YoutubeDownloader/ -o YoutubeDownloader/bin/Publish --configuration Release

    - name: Pack
      run: Compress-Archive -Path YoutubeDownloader/bin/Publish/* -DestinationPath YoutubeDownloader/bin/Publish/Archive.zip -Force
      shell: pwsh

    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          [Changelog](https://github.com/Tyrrrz/YoutubeDownloader/blob/master/Changelog.md)
        draft: false
        prerelease: false

    - name: Upload release asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: YoutubeDownloader/bin/Publish/Archive.zip
        asset_name: YoutubeDownloader.zip
        asset_content_type: application/zip

    - name: Notify Discord
      uses: satak/webrequest-action@v1.2.4
      with:
        url: ${{ secrets.DISCORD_WEBHOOK }}
        method: POST
        headers: |
          {
            "ContentType": "application/json; charset=UTF-8"
          }
        payload: |
          {
            "content": "**YoutubeDownloader** new version released!\nVersion: `${{ steps.get-version.outputs.tag }}`\nChangelog: <https://github.com/Tyrrrz/YoutubeDownloader/blob/${{ steps.get-version.outputs.tag }}/Changelog.md>"
          }
