name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        # Fixed version, workaround for https://github.com/dotnet/core/issues/7176
        dotnet-version: 6.0.100

    - name: Build & publish
      run: dotnet publish YoutubeDownloader/ -o YoutubeDownloader/bin/Publish --configuration Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: YoutubeDownloader
        path: YoutubeDownloader/bin/Publish
